### ISSUE TITLE
Asking for the dataset

### ISSUE THREAD

**Issue by harrytrinh2** [ilmonteux/project-phishing#10]
Hello, I did contact the authors to ask for the dataset, but I could not contact them. Could you please share the dataset with me?

**Comment by OrjwanZaafarani** [comment]
I'm having the same issue here. Can you please send it to me as well?

**Comment by midnightspecia1** [comment]
Hi there it seems like your build.sh fails with  ERROR 403: Forbidden.
Can you please share dataset and your trained models to some different place (gdrive maybe?) ?

**Comment by ilmonteux** [comment]
Hey everyone, sorry for the delay in answering.
- I have uploaded the full Logos in the Wild dataset dataset (both the source URLs i received from the paper authors, and the actual images I had downloaded in 2019) here: https://zenodo.org/record/5101018 .  I will update the README
- I can see why the trained models aren't available from the S3 bucket, let me check

**Comment by OrjwanZaafarani** [comment]
@ilmonteux Thank you very much for your cooperation!
