### ISSUE TITLE
tensorflow issue

### ISSUE THREAD

**Issue by kidboy-man** [ilmonteux/project-phishing#3]
I was trying to use the logohunter but got error when I run `python logohunter.py --test`
but seems had a problem with the tensorflow version. What tf version I need to run this script? is it possible run with non-GPU tensorflow?

Thank you

**Comment by ilmonteux** [comment]
Hi there,
it definitely can run without a GPU, I tested it on a MacBook Air (obviosuly slower than with a GPU), and it __should__ run independently of the tensorflow version. To be precise, it is running there with `tensorflow 1.5.1`, and it was also tested on `1.12`. 
The environment on the macbook was created as detailed in the README, and I just verified that it works with this
```
conda create -n logohunter python=3
conda activate logohunter
conda install matplotlib keras=2.2.4 pillow scikit-learn opencv=3.4.4
```
(with respect to the README, I dropped tensorflow-gpu. Basically you just want to make sure you can install tensorflow and opencv together, conda sometimes is weird about versioning and will tell you it can't find a package if it can't find a consistent set of dependencies across all packages)
