### ISSUE TITLE
Where is the yolo pre-trained model?

### ISSUE THREAD

**Issue by fantasycz** [ilmonteux/project-phishing#6]
Hi, ilmonteux. I really like your idea for the general purpose logo detection! And it seems it works perfect based on your example. I tried rerun it and use it with c++. I didn't find the pre-trained yolo model? Could you please show me? If you have time, could we have a short talk about this? BTW, I am also a student of UCI, Zot!

**Comment by ilmonteux** [comment]
Hey there, sorry I seemed to have notifications turned off and just saw this. The yolo weights pre-trained on the logo dataset are downloaded to the `src/keras_yolo3/` directory with the `build/build.sh` script.
