### ISSUE TITLE
Trying with YOLOv4

### ISSUE THREAD

**Issue by egesabanci** [ilmonteux/project-phishing#9]
Hi ilmonteux, this approach for similarity detection is perfect. Great work. 

I just wanna try your approach with YOLOv4 model weights which is trained for my own case. How can I do this?

Thanks.

**Comment by ilmonteux** [comment]
Hey, that's an interesting idea!
It depends how you have yolov4 implemented, but I would expect you'd be able to just drop a `yolo4` folder in `src` and modify the imports. The yolo3 model is in the `src/keras_yolo3` folder (which is a fork of the [qqwweee/keras-yolo3](https://github.com/qqwweee/keras-yolo3) repo), so changing all the `from keras_yolo3 import ...` calls (e.g. see this [code search](https://github.com/ilmonteux/logohunter/search?q=keras_yolo3)) to `from yolo4 import ...` (possibly copying over some helper functions if needed) should let you re-train your model with YOLOv4, and then run inference with that backend.

**Comment by egesabanci** [comment]
Thanks a lot, I wil try. 🙂
